### ISSUE TITLE
WAITING TO SEE EVOX FWB 

### ISSUE THREAD

**Issue by sarthakroy2002** [Crescent-OS/android_frameworks_base#2]
WHERE IS THE EVOX FWB SOR..I M WAITING TO SEE THAT 

ALSO ADD SMILEY GAMING HACKS PLOX,....THOSE ARE MUST FOR 69FPS

**Comment by Maitreya29** [comment]
BHAI PLEASE ALSO ADD CORVUS GAMING COMMITS

**Comment by sarthakroy2002** [comment]
> BHAI PLEASE ALSO ADD CORVUS GAMING COMMITS

CRESENT OS BHAAIIIEST ROM SOR....

**Comment by techyminati** [comment]
BHAI PLEASE ADD PUBG 240FPS UNLOCKER
